sudo: required

cache:
  directories:
  - $HOME/.composer/cache

language: node_js
node_js:
  - "8"

git:
  depth: 1

services:
  - docker
  - docker-compose

before_install:
  - docker --version
  - docker-compose --version
  - chmod +x ./travis_install.sh && ./travis_install.sh
  - travis_retry docker login -u ${DOCKERHUB_USER} -p ${DOCKERHUB_PASSWORD}
  - npm i -g @crazyfactory/docker-project-cli

install:
  - dopr pull && dopr up -d
  - dopr composer install
  - scripts/ci-install.sh

script:
  - dopr test

deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: false
  on:
    tags: true
