version: '3'

services:
  phalcon-loggers-php-fpm:
    image: crazyfactory/shopapi-php-fpm:7.3-dev
    container_name: phalcon-loggers-php-fpm
    volumes:
      - ../:/var/www/project
      - ./php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/z-overrides.ini
      - ../.composer:/root/composer
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
      COMPOSER_HOME: /root/composer
